# Generated by Django 5.1.4 on 2024-12-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='news')),
                ('author', models.CharField(max_length=100)),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
